
name: AsyncEnchantLimiter
version: ${version}
main: studio.jan1k.asyncenchantlimiter.AsyncEnchantLimiter
api-version: 1.20
authors: [Jan1k, Antigravity]
description: A high-performance, async enchantment limiter with zero bypasses.
folia-supported: true
softdepend: [EcoEnchants, AdvancedEnchantments]

commands:
  enchantlimiter:
    description: Main command for EnchantLimiter
    aliases: [el, elimiter]
    usage: /<command> [reload|gui]
    permission: enchantlimiter.admin

permissions:
  enchantlimiter.admin:
    description: Allows full access to EnchantLimiter configuration and reload.
    default: op
  enchantlimiter.bypass:
    description: Bypasses enchantment limits (if enabled in config).
    default: false
